name: Multitool

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

on:
  repository_dispatch:
    types: build-multitool-image
  push:
    paths:
      - .github/workflows/multitool.yml
      - 'multitool/**'
      - 'multitool-k8s/**'
      - 'multitool-aws/**'
      - 'multitool-tf/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push multitool
      working-directory: multitool/
      env:
        IMAGE_TAG: nyvanga/multitool:latest
      run: docker build . --file Dockerfile --tag $IMAGE_TAG && docker push $IMAGE_TAG

    - name: Build and push multitool-k8s
      working-directory: multitool-k8s/
      env:
        IMAGE_TAG: nyvanga/multitool-k8s:latest
      run: docker build . --file Dockerfile --tag $IMAGE_TAG && docker push $IMAGE_TAG

    - name: Build and push multitool-aws
      working-directory: multitool-aws/
      env:
        IMAGE_TAG: nyvanga/multitool-aws:latest
      run: docker build . --file Dockerfile --tag $IMAGE_TAG && docker push $IMAGE_TAG

    - name: Build and push multitool-tf
      working-directory: multitool-tf/
      run: ./build-images.sh
