name: Speedtest

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

on:
  repository_dispatch:
    types: build-speedtest-image
  push:
    paths:
      - .github/workflows/speedtest.yml
      - 'speedtest/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push speedtest
      working-directory: speedtest/
      env:
        IMAGE_TAG: nyvanga/speedtest:latest
      run: docker build . --file Dockerfile --tag $IMAGE_TAG && docker push $IMAGE_TAG
